import type {Metadata} from "next";
import {Raleway} from "next/font/google";
import "./globals.scss";
import Header from "./(home)/(header)";

const raleway = Raleway({subsets: ["latin", "cyrillic"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const RootLayout = ({children}: {children: React.ReactNode}) => {
	return (
		<html lang="en">
			<body className={raleway.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
